### ISSUE TITLE
pot_k calculation problem when example script executed

### ISSUE THREAD

**Issue by vinni94** [abtawfik/coupling-metrics#3]
https://github.com/abtawfik/coupling-metrics/blob/b70668c52f522789f104b49a5163ec9536dbb5a9/heated_condensation/static/hcfcalc.f90#L227
This issue is being raised with regard to calculation of potential temperature while running example cases. while handling missing data, last indices have arbitrary values  instead of missing/nan. I am not sure whether I am running this properly. or it might be a problem from my end. Thank you for the code. Big fan of your work!

**Comment by abtawfik** [comment]
I think you found a bug here.  It looks like pot_k was never initialized with missing data before assignment above which means if tmp_k or press are missing then pot_k will contain a strange/incorrect missing number that is dependent on your system and compiler.
Good catch!``

**Comment by abtawfik** [comment]
Issue should be fixed with last push.  
Let me know if that worked so I can close the issue.

**Comment by vinni94** [comment]
Tq very much sir. Big fan of your work.
Regards,

VINAYAK HUGGANNAVAR
Research Scholar,
Civil Engineering Department,
Indian Institute of Technology Bombay, Powai
Mumbai-400076

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
11/17/19,
2:07:28 PM

**Comment by vinni94** [comment]
I will run the code once and will let you know

**Comment by vinni94** [comment]
Code works fine now
